[build]
  publish = "public"  # The folder containing your index.html
  functions = "netlify/functions"  # The folder containing the serverless function

[[redirects]]
  from = "/v1/redirect"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
